      SUBROUTINE INTER
C                                                                       
C     **************************************************************    
C                                                                       
C	  THIS SUBROUTINE CALCULATES THE NOZZLE RADIUS AND OUTER NORMAL     
C                                                                       
C     **************************************************************    
C                                                                       
      COMMON /AV/ IAV,CAV,NST,SMP,LSS,CTA,XMU,XLA,RKMU,QUT(81,21),QVT(81
     1,21),QPT(81,21)                                                   
      COMMON /ONESID/ UD(4),VD(4),PD(4),ROD(4)                          
      COMMON /SOLUTN/ U(81,21,2),V(81,21,2),P(81,21,2),RO(81,21,2)      
      COMMON /CNTRLC/ LMAX,MMAX,NMAX,NPRINT,TCONV,FDT,GAMMA,RGAS,GAM1,GA
     1M2,L1,L2,L3,M1,M2,DX,DY,DT,N,N1,N3,NASM,IVEL,ICHAR,N1D,LJET,JFLAG,
     2IERR,IUI,IUO,DXR,DYR,LD,MD,LMD1,LMD3,IB,RSTAR,RSTARS,NPLOT,G,PC,TC
     3,LC,PLOW,ROLOW                                                    
      COMMON /GEMTRYC/ NGEOM,XI,RI,XT,RT,XE,RE,RCI,RCT,ANGI,ANGE,XW(81),
     1YW(81),XWI(81),YWI(81),NXNY(81),NWPTS,IINT,IDIF,LT,NDIM           
      COMMON /GCB/ NGCB,XICB,RICB,XTCB,RTCB,XECB,RECB,RCICB,RCTCB,ANGICB
     2,ANGECB,XCB(81),YCB(81),XCBI(81),YCBI(81),NXNYCB(81),NCBPTS,IINTCB
     3,IDIFCB,LECB                                                      
      COMMON /BCC/ PT(21),TT(21),THETA(21),PE,MASSE,MASSI,MASST,THRUST,N
     1STAG                                                              
      REAL MN3,NXNY,MASSI,MASST,NXNYCB,MASSE   
C
	ATERM=0.0
	IF (ICHAR,EQ,2) GO TO 40
C
C	COMPUTE THE TENTATIVE SOLUTION AT T+DT
C
	MDUM=1
	IF (NGCB.NE.0) MDUM=2
	DO 30 L=2,LMAX
	DO 30 M=MDUM,M1
	CALL MAP (1,L,M,AL,BE,DE,LD1,AL1,BE1,DE1)
	LMD2=LD*(M-1)
	LMN1=L+LMD2+LMD1
	LMN3=L+LMD2+LMD3
	L1MN1=L-1+LMD2+LMD1
	LM1N1=L+LD*(M-2)+LMD1
	UB=U(LMN1)
	VB=V(LMN1)
	PB=P(LMN1)
	ROB=RO(LMN1)
	ASB=GAMMA*PB/ROB
	IF (M.NE.1) GO TO 10
	DUDX=(UB-U(L1MN1))*DXR
	DPDX=(PB-P(L1MN1))*DXR
	DRODX=(ROB-RO(L1MN1))*DXR
	DVDY=(4.0*V(L,2,N1)-V(L,3,N1))*0.5*DYR
	V(LMN3)=0.0
C
	URHS=-UB*DUDX-DPDX/ROB
	RORHS=-UB*DRODX-ROB*DUDX-(1+NDIM)*ROB*BE*DVDY
	PRHS=-UB*DPDX+ASB*(RORHS+UB*DRODX)
	GO TO 20
10	IF (NDIM.EQ.1) ATERM=ROB*VB/((M-1)*DY/BE+YCB(L))
	UVB=UB+AL+VB*BE+DE
	DUDX=(UB-U(L1MN1))*DXR
	DVDX=(VB-V(L1MN1))*DXR
	DPDX=(PB-P(L1MN1))*DXR
	DRODX=(ROB-RO(L1MN1))*DXR
	DUDY=(UB-U(LM1N1))*DYR
	DVDY=(VB-V(LM1N1))*DYR
	DPDY=(PB-P(LM1N1))*DYR
	DRODY=(ROB-RO(LM1N1))*DYR
C
	URHS=-UB*DUDX-UVB*DUDY-(DPDX+AL*DPDY)/ROB
	VRHS=-UB*DVDX-UVB*DVDY-BE*DPDY/ROB
	RORHS=-UB*DRODX-UVB*DRODY-ROB*(DUDX+AL*DUDY+BE*DVDY)-ATERM
	PRHS=-UB*DPDX-UVB*DPDY+ASB*(RORHS+UB*DRODX+UVB*DRODY)
	V(LMN3)=V(LMN1)+VRHS*DT
20	U(LMN3)=U(LMN1)+URHS*DT
	P(LMN3)=P(LMN1)+PRHS*DT
	RO(LMN3)=RO(LMN1)+RORHS*DT
	IF (P(LMN3).LE.0.0) P(LMN3)=PLOW*PC
	IF (RO(LMN3).LE.0.0) RO(LMN3)=ROLOW/G
30	CONTINUE
	RETURN
C
C	COMPUTE THE FINAL SOLUTION AT T+DT
C
40	MDUM=1
	IF (NGCB.NE.0) MDUM=2
	DO 70, L=2,L1
	DO 70 M=MDUM,M1
	CALL MAP (1,L,M,AL,BE,DE,LD1,AL1,BE1,DE1)
	LMD2=LD*(M-1)
	LMN1=L+LMD2+LMD1
	LMN3=L+LMD2+LMD3
	L1MN3=L+1+LMD2+LMD3
	LM1N3=L+LD*M+LMD3
	UB=U(LMN3)
	VB=V(LMN3)
	PB=P(LMN3)
	ROB=RO(LMN3)
	ASB=GAMMA*PB/ROB
	IF (M.NE.1) GO TO 50
	DUDX=(U(L1MN3)-UB)*DXR
	DPDX=(P(L1MN1)-PB)*DXR
	DRODX=(RO(L1MN1)-ROB)*DXR
	DVDY=(4.0*V(L,2,N3)-V(L,3,N3))*0.5*DYR
	V(LMN3)=0.0
C
	URHS=-UB*DUDX-DPDX/ROB
	RORHS=-UB*DRODX-ROB*DUDX-(1+NDIM)*ROB*BE*DVDY
	PRHS=-UB*DPDX+ASB*(RORHS+UB*DRODX)
	GO TO 60
50	IF (NDIM.EQ.1) ATERM=ROB*VB/((M-1)*DY/BE+YCB(L))
	UVB=UB+AL+VB*BE+DE
	DUDX=(U(L1MN3)-UB)*DXR
	DVDX=(V(L1MN3)-VB)*DXR
	DPDX=(P(L1MN3)-PB)*DXR
	DRODX=(RO(L1MN3)-ROB)*DXR
	DUDY=(U(LM1N3)-UB)*DYR
	DVDY=(V(LM1N3)-VB)*DYR
	DPDY=(P(LM1N3)-PB)*DYR
	DRODY=(RO(LM1N3)-ROB)*DYR
C
	URHS=-UB*DUDX-UVB*DUDY-(DPDX+AL*DPDY)/ROB
	VRHS=-UB*DVDX-UVB*DVDY-BE*DPDY/ROB
	RORHS=-UB*DRODX-UVB*DRODY-ROB*(DUDX+AL*DUDY+BE*DVDY)-ATERM
	PRHS=-UB*DPDX-UVB*DPDY+ASB*(RORHS+UB*DRODX+UVB*DRODY)
	V(LMN3)=(V(LMN1)+V(LMN3)+VRHS*DT)*0.5
60 	U(LMN3)=(U(LMN1)+U(LMN3)+URHS*DT)*0.5
	P(LMN3)=(P(LMN1)+P(LMN3)+PRHS*DT)*0.5
	RO(LMN3)=(RO(LMN1)+RO(LMN3)+RORHS*DT)*0.5
	IF (P(LMN3).LE.0.0) P(LMN3)=PLOW*PC
	IF (RO(LMN3).LE.0.0) RO(LMN3)=ROLOW/G
	IF (IAV.EQ.0) GO TO 70
C
C	ADD THE ARTIFICIAL VISCOSITY FOR SHOCK CALCULATIONS
C
	U(LMN3)=U(LMN3)+QUT(L,M)
	V(LMN3)=V(LMN3)+QVT(L,M)
	IF (M.EQ.1) V(LMN3)=0.0
	P(LMN3)=P(LMN3)+QPT(L,M)
70  CONTINUE
	RETURN
	END






	

