      PROGRAM MAIN
      IMPLICIT NONE
      
      INTEGER :: INPUT, OUTPUT, FILM
      REAL :: TCONV, FDT, TSTOP
      INTEGER :: NASM, NSTAG, NPRINT, NGCB, IINTCB, IDIFCB, NSTART
      REAL :: TSTART, GAMMA, RGAS
      INTEGER :: IUI, IUO, SMP
      INTEGER :: IPUNCH, IAV, CAV, NPLOT, IEX, LSS, CTA
      REAL :: XMU, XLA, RKMU, PLOW, ROLOW
      INTEGER :: IUNIT
      
      INTEGER :: LMAX, MMAX, NMAX, L1, L2, L3, M1, M2, N, N1, NJ, NASM
      INTEGER :: IVEL, ICMAR, N1D, LJET, JFLAG, IERR, DXR, DYR
      INTEGER :: LO, MD, LMD1, LMDJ, IB, RSTAR, R3TARS, NPLOT, G
      REAL :: PC, TC, PLOW, ROLOW
      
      INTEGER :: NGEOM, NWPTS, IINT, IDIF, LT, NDIM
      REAL :: XI, RI, XT, RT, XE, RE, RCI, RCT, ANGI, ANGE
      INTEGER :: NXNY(21), XWI(81), YWI(81)
      
      INTEGER :: NGCB, NCBPTS, LECB
      REAL :: XICB, RICB, XTCB, RTCB, XECB, RECB, RCICB, RCTCB, ANGICB, ANGECB
      INTEGER :: XCBI(81), YCBI(81), NXNYCB(81)
      
      REAL :: PT(2), TT(21), THETA(21), PE, MASSE, MASSI, MASST, THRUST, NSTAG
      
      NAMELIST /CNTRL/ LMAX, MMAX, NMAX, NPRINT, TCONV, FDT, TSTOP, &
     & NASM, NSTAG, NAME, NCONVI, NST, IUI, IUO, SMP, IPUNCH, IAV, &
     & CAV, NPLOT, IEX, LSS, CTA, XMU, XLA, RKMU, IUNIT, PLOW, ROLOW
      NAMELIST /IVS/ U, V, P, R0, N1D, NSTART, TSTART, RSTAR, RSTARS
      NAMELIST /GEMTRY/ NDIM, XI, RI, RT, XE, RE, RCI, RCT, ANGI, &
     & ANGE, NGEOM, XWI, YWI, NWPTS, IINT, IDIF, LJET, JFLAG, NXNY
      NAMELIST /GCBL/ NGCB, XICB, RICB, XTCB, RTCB, XECB, RECB, &
     & RCICB, RCTCB, ANGICB, ANGECB, XCBI, YCBI, NXNYCB, NCBPTS, &
     & IINTCB, IDIFCB, LECB
      NAMELIST /BC/ PT, TT, THETA, PE, NSTAG, ISUPER, UI, VI, PI, R0
      
      OPEN(UNIT=INPUT, FILE='INPUT')
      OPEN(UNIT=OUTPUT, FILE='OUTPUT')
      OPEN(UNIT=FILM, FILE='FILM')
      
      READ(5, CNTRL)
      READ(5, IVS)
      READ(5, GEMTRY)
      READ(5, GCBL)
      READ(5, BC)
      
      WRITE(OUTPUT, CNTRL)
      WRITE(OUTPUT, IVS)
      WRITE(OUTPUT, GEMTRY)
      WRITE(OUTPUT, GCBL)
      WRITE(OUTPUT, BC)
      
      CLOSE(5)
      
      END PROGRAM MAIN
